name: "WordPress version checker"

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'WordPress version checker'
  schedule:
    - cron: '0 0 * * 0'

permissions:
  issues: write

jobs:
  wordpress-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: WordPress version checker
        uses: skaut/wordpress-version-checker@v2.0.0
        with:
          repo-token: ${{ secrets.TOKEN }}
